import Mathlib
import Cad.Multivariate.ProjectionTheorem.Basic
import Cad.Multivariate.ProjectionTheorem.DiscrMul

/-!
# Discriminant facts for Brown's theorem

The classical fact, not in Mathlib, needed to recover Brown's original
Theorem 3.1 from the pipeline form `brown_generalized` with witness `P = disc f`:

* **Fact A** (`discr_mem_span`): `C (disc f) ∈ ⟨f, f'⟩` for `f` of degree `≥ 2`
  with `natDegree f` invertible.  The resultant only gives `lc · disc ∈ ⟨f, f'⟩`;
  to remove the `lc` factor we use the polar polynomial `g = n·f - X·f'` and the
  identity `lc(f') · Res(f', g) = n^{n-1} · Res(f', f)` (pure resultant calculus),
  cancelling `n · lc` in the domain.

The pipeline form needs only this single membership; the reverse membership
(Brown's Lemma 8.1, `disc (reverse f) = disc f`, and its resultant-reindexing
proof) required by the homogenization route is no longer used.
-/

noncomputable section

open Polynomial

namespace Brown

variable {R : Type*} [CommRing R] [IsDomain R]

/-! ### Fact A: the discriminant lies in `⟨f, f'⟩` -/

/-- **Fact A.**  For `f` of degree `≥ 2` with `natDegree f` invertible in the
domain `R`, the discriminant lies in the ideal generated by `f` and `f'`. -/
theorem discr_mem_span (f : R[X])
    (hdeg : 2 ≤ f.natDegree) (hn : IsUnit (f.natDegree : R)) :
    C f.discr ∈ Ideal.span ({f, derivative f} : Set R[X]) := by
  have hf_ne : f ≠ 0 := ne_zero_of_natDegree_gt (by omega : 0 < f.natDegree)
  have hlc_ne : f.leadingCoeff ≠ 0 := leadingCoeff_ne_zero.mpr hf_ne
  have hn_ne : (f.natDegree : R) ≠ 0 := hn.ne_zero
  have hf'_deg : (derivative f).natDegree ≤ f.natDegree - 1 := natDegree_derivative_le f
  -- the polar polynomial `g = n·f - X·f'`
  set g : R[X] := C (f.natDegree : R) * f - X * derivative f with hg_def
  -- `f'.coeff (n-1) = n · lc`
  have hlcf' : (derivative f).coeff (f.natDegree - 1) = (f.natDegree : R) * f.leadingCoeff := by
    rw [coeff_derivative, show f.natDegree - 1 + 1 = f.natDegree from by omega, coeff_natDegree,
      Nat.cast_sub (show 1 ≤ f.natDegree from by omega)]
    ring
  -- `g` has degree `≤ n-1`
  have hg_deg : g.natDegree ≤ f.natDegree - 1 := by
    rw [Polynomial.natDegree_le_iff_coeff_eq_zero]
    intro m hm
    rw [hg_def, coeff_sub, coeff_C_mul]
    obtain ⟨m', rfl⟩ : ∃ m', m = m' + 1 := ⟨m - 1, by omega⟩
    rw [coeff_X_mul]
    by_cases hmn1 : m' + 1 = f.natDegree
    · rw [hmn1, coeff_natDegree, show m' = f.natDegree - 1 from by omega, hlcf']
      ring
    · have h1 : f.coeff (m' + 1) = 0 := coeff_eq_zero_of_natDegree_lt (by omega)
      have h2 : (derivative f).coeff m' = 0 := coeff_eq_zero_of_natDegree_lt (by omega)
      rw [h1, h2]; ring
  -- (A): `Res(f', g, n-1, n) = n^{n-1} · Res(f', f, n-1, n)`
  have hgform : g = C (f.natDegree : R) * f + derivative f * (-X) := by rw [hg_def]; ring
  have hA : resultant (derivative f) g (f.natDegree - 1) f.natDegree
      = (f.natDegree : R) ^ (f.natDegree - 1) *
        resultant (derivative f) f (f.natDegree - 1) f.natDegree := by
    rw [hgform,
      resultant_add_mul_right (derivative f) (C (f.natDegree : R) * f) (-X)
        (f.natDegree - 1) f.natDegree
        (by simpa using (by omega : 1 + (f.natDegree - 1) ≤ f.natDegree)) hf'_deg,
      resultant_C_mul_right (derivative f) f (f.natDegree - 1) f.natDegree (f.natDegree : R)]
  -- (B): `Res(f', g, n-1, n) = f'.coeff(n-1) · Res(f', g, n-1, n-1)`
  have hB : resultant (derivative f) g (f.natDegree - 1) f.natDegree
      = (derivative f).coeff (f.natDegree - 1) *
        resultant (derivative f) g (f.natDegree - 1) (f.natDegree - 1) := by
    have h := resultant_add_right_deg (derivative f) g (f.natDegree - 1) (f.natDegree - 1) 1 hg_deg
    rwa [show f.natDegree - 1 + 1 = f.natDegree from by omega, pow_one] at h
  -- combine and reduce to disc
  have hpos : (0 : WithBot ℕ) < f.degree :=
    natDegree_pos_iff_degree_pos.mp (by omega)
  have hcomm : resultant (derivative f) f (f.natDegree - 1) f.natDegree
      = (-1) ^ ((f.natDegree - 1) * f.natDegree) *
        resultant f (derivative f) f.natDegree (f.natDegree - 1) :=
    resultant_comm (derivative f) f (f.natDegree - 1) f.natDegree
  have hderiv := resultant_deriv hpos
  set R0 : R := resultant (derivative f) g (f.natDegree - 1) (f.natDegree - 1) with hR0_def
  -- the unit factor
  set s : R := (-1) ^ ((f.natDegree - 1) * f.natDegree) *
    (-1) ^ (f.natDegree * (f.natDegree - 1) / 2) with hs_def
  have hs : IsUnit s := by
    rw [hs_def]
    exact ((isUnit_one.neg).pow _).mul ((isUnit_one.neg).pow _)
  -- key scalar equation: `n · lc · R0 = n^{n-1} · s · lc · disc`
  have key : (f.natDegree : R) * f.leadingCoeff * R0
      = (f.natDegree : R) ^ (f.natDegree - 1) * s * f.leadingCoeff * f.discr := by
    have e := hB.symm.trans hA
    rw [hlcf', hR0_def] at e
    rw [hcomm, hderiv] at e
    rw [hs_def]
    linear_combination e
  -- cancel `n · lc`
  have hpow : (f.natDegree : R) ^ (f.natDegree - 1)
      = (f.natDegree : R) * (f.natDegree : R) ^ (f.natDegree - 2) := by
    conv_lhs => rw [show f.natDegree - 1 = (f.natDegree - 2) + 1 from by omega]
    rw [pow_succ']
  have hne : (f.natDegree : R) * f.leadingCoeff ≠ 0 := mul_ne_zero hn_ne hlc_ne
  have hR0 : R0 = (f.natDegree : R) ^ (f.natDegree - 2) * s * f.discr := by
    apply mul_left_cancel₀ hne
    rw [key, hpow]; ring
  -- membership: `C R0 ∈ ⟨f', g⟩ ⊆ ⟨f, f'⟩`
  obtain ⟨p, q, _, _, hbez⟩ := exists_mul_add_mul_eq_C_resultant (m := f.natDegree - 1)
    (n := f.natDegree - 1) (derivative f) g hf'_deg hg_deg (Or.inl (by omega))
  rw [← hR0_def] at hbez
  have hmem_fg' : C R0 ∈ Ideal.span ({derivative f, g} : Set R[X]) :=
    Ideal.mem_span_pair.mpr ⟨p, q, by rw [mul_comm p (derivative f), mul_comm q g]; exact hbez⟩
  have hsub : Ideal.span ({derivative f, g} : Set R[X]) ≤
      Ideal.span ({f, derivative f} : Set R[X]) := by
    rw [Ideal.span_le]
    intro x hx
    rcases hx with rfl | hx
    · exact Ideal.subset_span (Set.mem_insert_of_mem _ rfl)
    · rw [Set.mem_singleton_iff] at hx
      subst hx
      rw [hg_def]
      exact sub_mem
        (Ideal.mul_mem_left _ _ (Ideal.subset_span (Set.mem_insert _ _)))
        (Ideal.mul_mem_left _ _ (Ideal.subset_span (Set.mem_insert_of_mem _ rfl)))
  have hCR0 : C R0 ∈ Ideal.span ({f, derivative f} : Set R[X]) := hsub hmem_fg'
  -- divide by the unit `C (n^{n-2} · s)`
  have hu : IsUnit (C ((f.natDegree : R) ^ (f.natDegree - 2) * s) : R[X]) :=
    isUnit_C.mpr ((hn.pow _).mul hs)
  obtain ⟨u, hu_eq⟩ := hu
  have hCR0_eq : C R0 = (u : R[X]) * C f.discr := by
    rw [hR0, hu_eq, ← map_mul]
  have : C f.discr = (↑u⁻¹ : R[X]) * C R0 := by
    rw [hCR0_eq, ← mul_assoc, Units.inv_mul, one_mul]
  rw [this]
  exact Ideal.mul_mem_left _ _ hCR0

end Brown

